### ISSUE TITLE
cmusphinx/g2p-seq2seq + beam search

### ISSUE THREAD

**Issue by madhavsund** [pbhatia243/Neural_Conversation_Models#2]
while trying to decode the model ( trained using https://github.com/cmusphinx/g2p-seq2seq)  with beam search I get the following error

Replies --------------------------------------->
Traceback (most recent call last):
  File "neural_conversation_model.py", line 323, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "neural_conversation_model.py", line 318, in main
    decode()
  File "neural_conversation_model.py", line 275, in decode
    rec = " ".join([tf.compat.as_str(rev_vocab[output]) for output in foutputs])
IndexError: list index out of range

**Comment by pbhatia243** [comment]
I am not sure how that code can be applied here .
