### ISSUE TITLE
Beam search not working when tensorflow is updated

### ISSUE THREAD

**Issue by anutammewar** [pbhatia243/Neural_Conversation_Models#5]
I updated tensorflow (now tensorflow-gpu==0.12.0rc0) and now I'm not being able to use beam search while decoding. It throws this error:

Traceback (most recent call last):
  File "neural_conversation_model.py", line 323, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "neural_conversation_model.py", line 318, in main
    decode()
  File "neural_conversation_model.py", line 230, in decode
    model = create_model(sess, True, beam_search=beam_search, beam_size=beam_size, attention=attention)
  File "neural_conversation_model.py", line 104, in create_model
    forward_only=forward_only, beam_search=beam_search, beam_size=beam_size, attention=attention)
  File "/home/ubuntu/reminders_dump/seq_to_seq/seq2seq_model.py", line 138, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/home/ubuntu/reminders_dump/seq_to_seq/my_seq2seq.py", line 1044, in decode_model_with_buckets
    decoder_inputs[:bucket[1]])
  File "/home/ubuntu/reminders_dump/seq_to_seq/seq2seq_model.py", line 137, in <lambda>
    self.target_weights, buckets, lambda x, y: seq2seq_f(x, y, True),
  File "/home/ubuntu/reminders_dump/seq_to_seq/seq2seq_model.py", line 112, in seq2seq_f
    beam_size=beam_size )
  File "/home/ubuntu/reminders_dump/seq_to_seq/my_seq2seq.py", line 365, in embedding_rnn_seq2seq
    feed_previous=feed_previous, beam_search=beam_search, beam_size=beam_size)
  File "/home/ubuntu/reminders_dump/seq_to_seq/my_seq2seq.py", line 299, in embedding_rnn_decoder
    loop_function=loop_function,output_projection=output_projection, beam_size=beam_size)
  File "/home/ubuntu/reminders_dump/seq_to_seq/my_seq2seq.py", line 203, in beam_rnn_decoder
    state_size = int(initial_state.get_shape().with_rank(2)[1])
AttributeError: 'tuple' object has no attribute 'get_shape'

Maybe this is related to : https://github.com/tensorflow/tensorflow/issues/3056

**Comment by pbhatia243** [comment]
Updated with latest version.
