### ISSUE TITLE
not compatile with the newest tf

### ISSUE THREAD

**Issue by SeekPoint** [pbhatia243/Neural_Conversation_Models#9]
mldl@mldlUB1604:/media/mldl/data1t/os_prj/Neural_Conversation_Models$ sudo python neural_conversation_model.py --train_dir ubuntu/ --en_vocab_size 60000 --size 512 --data_path ubuntu/train.tsv --dev_data ubuntu/valid.tsv --vocab_path ubuntu/60k_vocan.en --attention --decode --beam_search --beam_size 25
[sudo] password for mldl: 
2017-02-03 02:41:44: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcublas.so.8.0 locally
2017-02-03 02:41:44: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
2017-02-03 02:41:44: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
2017-02-03 02:41:44: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
2017-02-03 02:41:44: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "neural_conversation_model.py", line 29, in <module>
    from  seq2seq_model import *
  File "/media/mldl/data1t/os_prj/Neural_Conversation_Models/seq2seq_model.py", line 12, in <module>
    from my_seq2seq import *
  File "/media/mldl/data1t/os_prj/Neural_Conversation_Models/my_seq2seq.py", line 41, in <module>
    from tensorflow.python.ops import rnn_cell
ImportError: cannot import name rnn_cell
mldl@mldlUB1604:/media/mldl/data1t/os_prj/Neural_Conversation_Models$

**Comment by pbhatia243** [comment]
Updated with latest version.
